In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

def kernel(point,xmat,k):
    m,n=np.shape(xmat)
    weights=np.mat(np.eye((m)))
    for j in range(m):
        diff=point-X[j]
        weights[j,j]=np.exp(diff*diff.T/(-2.0*k**2))
    return weights

def localWeight(point,xmat,ymat,k):
    wei=kernel(point,xmat,k)
    W=(X.T*(wei*X)).I*(X.T*(wei*ymat.T))
    return W

def localWeightRegression(xmat,ymat,k):
    m,n=np.shape(xmat)
    ypred=np.zeros(m)
    for i in range(m):
        ypred[i]=xmat[i]*localWeight(xmat[i],xmat,ymat,k)
    return ypred

def graphPlot(X,ypred):
    sortindex=X[:,1].argsort(0)
    print("sort index : ",sortindex)    
    xsort=X[sortindex][:,0]
    print("X sort : ",xsort)
    fig=plt.figure()
    ax=fig.add_subplot(1,1,1)
    ax.scatter(bill,tip,color='green')
    ax.plot(xsort[:,1],ypred[sortindex],color='red',linewidth=5)
    plt.xlabel('Total bill')
    plt.ylabel('Tip')
    plt.show()

data=pd.read_csv('data9.csv')
bill=np.array(data.total_bill)
tip=np.array(data.tip)
mbill=np.mat(bill)
print("Mbill : ",mbill)
mtip=np.mat(tip)
print("MTip : ",mtip)
m=np.shape(mbill)[1]
one=np.mat((np.ones(m)))
print("one : ",one)
X=np.hstack((one.T,mbill.T))
print("X : ",X)
ypred=localWeightRegression(X,mtip,5)
graphPlot(X,ypred)

ModuleNotFoundError: No module named 'pandas'

In [6]:
X=np.array([[3,10],[1,5],[2,8],[4,2]])
print(X)
sortindex=X[:,1].argsort(0)
Xsort=X[sortindex][:,0]
print("Original data\n",X)
print("Sortindex\n",sortindex)
print("Xsort data\n",Xsort)

[[ 3 10]
 [ 1  5]
 [ 2  8]
 [ 4  2]]
Original data
 [[ 3 10]
 [ 1  5]
 [ 2  8]
 [ 4  2]]
Sortindex
 [3 1 2 0]
Xsort data
 [4 1 2 3]
